#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
USE_PROCD=1
PROG=/usr/sbin/lighttpd

start_service() {
	[ -d /var/log/lighttpd ] || mkdir -p /var/log/lighttpd
	rm -rf /var/log/lighttpd/error.log
	chmod 0777 /var/log/lighttpd
	procd_open_instance
	procd_set_param command /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
	procd_set_param respawn
	procd_close_instance
}
