#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99

boot() {
	/usr/bin/http_event_inform &
}

start() {
	/usr/bin/http_event_inform &
}

stop() {
        killall -9 http_event_inform
}

